### PR TITLE
[NUI] Reduce code duplication - refactor dispose codes

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Refactor dispose codes to reduce code duplication

### API Changes ###

 - ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-274

### CODE REVIEW

**Review by liangliangzh — APPROVED** [review]
it's ok

**Review by junqingma — APPROVED** [review]
Looks fine

**Comment by dongsug-song** [comment]
Hello, Mr. Teng
please check the API-Breaks (just check the NUI APIs)
I recommend  to add [EditorBrowserble] attribute and process the ACR as "deprecated"
Thank you.

**Comment by dongsug-song** [comment]
[TizenFX.zip](https://github.com/dalihub/TizenFX/files/3567650/TizenFX.zip)


Hello, Mr. Teng
please check the attached API list CSV files.
it seems to break API-compatibility even though Dispose() is declared as parent's method.
**I think we need ACR if this is really required to fix SAM issue.**
thank you.

**Comment by elishateng** [comment]
> [TizenFX.zip](https://github.com/dalihub/TizenFX/files/3567650/TizenFX.zip)
> 
> Hello, Mr. Teng
> please check the attached API list CSV files.
> it seems to break API-compatibility even though Dispose() is declared as parent's method.
> **I think we need ACR if this is really required to fix SAM issue.**
> thank you.

Hello, Mr. SSong,
I'll write ACR for this patch. Thanks for your remind.

**Review by hyunjushin — APPROVED** [review]

**Review by hyunjushin — APPROVED** [review]

**Review by hyunjushin — COMMENTED** [review]
ok

**Review by hyunjushin — COMMENTED** [review]
ok

**Pull request merged**
