### PR TITLE
[NUI] Split large files

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Split NUIConstants, VisualMaps, AccessibilityManager, Window file

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by junqingma — APPROVED** [review]
looks good to me

**Review by huayongxu — APPROVED** [review]
It is good.

**Comment by hyunjushin** [comment]
View is the biggest class. I can't find partial class of View.

**Comment by elishateng** [comment]
> View is the biggest class. I can't find partial class of View.

Hello, Ms. Shin, View split will be pushed in next patch, after this patch https://github.com/dalihub/TizenFX/pull/14 (include view changed) merged,

**Pull request merged**
