### PR TITLE
[NUI] Split other large files

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. View splited into View,ViewBindableProperty,ViewEnum,ViewEvent,ViewInternal,ViewPublicMethods;
2. TextEditor splited into TextEditor,TextEditorBindableProperty,TextEditorEvent;
3. TextField splited into TextField,TextFieldBindableProperty,TextFieldEvent;
4. ScrollView splited into ScrollView,ScrollViewBindableProperty,ScrollViewEvent;
5. Property splited into Property,KeyValue,PropertyArray,PropertyKey,PropertyMap,PropertyValue;

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AdunFang — APPROVED** [review]
Seems no problem.

**Review by huayongxu — APPROVED** [review]
It is good.

**Review by junqingma — APPROVED** [review]
looks fine to me

**Review by dongsug-song — APPROVED** [review]

**Comment by dongsug-song** [comment]
Please upload this patch on Samsung/TizenFX also

**Comment by adeelkazmi** [comment]
Please use Samsung/TizenFX. I'm closing this pull request.

**Pull request closed without merging**
