### PR TITLE
[NUI] Layouting made public

### PR DESCRIPTION
**Pull request by agnelovaz**
### Description of Change ###
NUI Layouting API made public
LayoutGroup _children property renamed to LayoutChildren

Classes that were previously marked internal now public.

Change-Id: I78b0a54c07d69496a666740fd6e09ade1dd6bc9b

### API Changes ###
http://suprem.sec.samsung.net/jira/browse/TCSACR-278

Added:
public AbsoluteLayout()
  protected override void OnMeasure(MeasureSpecification widthMeasureSpec,MeasureSpecification heightMeasureSpec)
  protected override void OnLayout(bool changed, LayoutLength left, LayoutLength top, LayoutLength right, LayoutLength bottom)

src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
  public class FlexLayout
  protected virtual void Dispose(DisposeTypes type)
  public FlexLayout()
  public FlexDirection Direction
  public FlexJustification Justification
  public FlexWrapType WrapType
  public AlignmentType Alignment
  public AlignmentType ItemsAlignment
  public enum FlexDirection
  public enum FlexJustification
  public enum FlexWrapType
  public enum AlignmentType
  protected override void OnChildAdd(LayoutItem child)
  protected override void OnChildRemove(LayoutItem child)
  protected override void OnMeasure( MeasureSpecification widthMeasureSpec, MeasureSpecification heightMeasureSpec )
  protected override void OnLayout( bool changed, LayoutLength left, LayoutLength top, LayoutLength right, LayoutLength bottom )

/Layouting/GridLayout.cs
  public class GridLayout
  public GridLayout()
  public int Columns
  protected override void OnMeasure( MeasureSpecification widthMeasureSpec, MeasureSpecification heightMeasureSpec )
  protected override void OnLayout( bool changed, LayoutLength left, LayoutLength top, LayoutLength right, LayoutLength bottom )

src/Tizen.NUI/src/public/Layouting/ILayoutParent.cs 
public interface ILayoutParent
void Add(LayoutItem layoutItem);
void Remove(LayoutItem layoutItem);

src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
public class LayoutGroup 
    protected List<LayoutItem> LayoutChildren{ get;}
    public LayoutGroup()
    public LayoutGroup(View owner)
    public virtual void Add(LayoutItem childLayout)
    public void RemoveAll()
    public virtual void Remove(LayoutItem layoutItem)

        public static MeasureSpecification GetChildMeasureSpecification(MeasureSpecification parentMeasureSpec, LayoutLength padding, LayoutLength childDimension)

        protected override void OnMeasure(MeasureSpecification widthMeasureSpec, MeasureSpecification heightMeasureSpec)

        protected override void OnLayout(bool changed, LayoutLength left, LayoutLength top, LayoutLength right, LayoutLength bottom)

        protected override void OnSizeChanged(LayoutSize newSize, LayoutSize oldSize)

        protected override void OnAttachedToOwner()

        protected virtual void OnChildAdd(LayoutItem child)

        protected virtual void OnChildRemove(LayoutItem child)

    protected virtual void MeasureChild(LayoutItem child, MeasureSpecification parentWidthMeasureSpec, MeasureSpecification parentHeightMeasureSpec)

    protected virtual void MeasureChildWithMargins(LayoutItem child, MeasureSpecification parentWidthMeasureSpec, LayoutLength widthUsed, MeasureSpecification parentHeightMeasureSpec, LayoutLength heightUsed)

src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
public class LayoutItem
    public TransitionCondition ConditionForAnimation
    public void Unparent()
    public View Owner
    public bool Animate
    public Extents Margin
    public Extents Padding
    public LayoutItem()
    public LayoutItem(View owner)
    public void SetParent( ILayoutParent parent)
    public void Unparent()

    protected void Measure(MeasureSpecification widthMeasureSpec, MeasureSpecification heightMeasureSpec)
    public void Layout(LayoutLength left, LayoutLength top, LayoutLength right, LayoutLength bottom)
    public static LayoutLength GetDefaultSize(LayoutLength size, MeasureSpecification measureSpecification)
    public ILayoutParent GetParent()
    public void RequestLayout()

    public MeasuredSize MeasuredWidth
    public MeasuredSize MeasuredHeight

    public MeasuredSize MeasuredWidthAndState

    public MeasuredSize MeasuredHeightAndState

    public LayoutLength SuggestedMinimumWidth

    public LayoutLength SuggestedMinimumHeight

    public LayoutLength MinimumWidth

    public LayoutLength MinimumHeight

    protected MeasuredSize ResolveSizeAndState( LayoutLength size, MeasureSpecification measureSpecification, MeasuredSize.StateType childMeasuredState )

    protected void SetMeasuredDimensions( MeasuredSize measuredWidth, MeasuredSize measuredHeight )

    protected virtual void OnMeasure(MeasureSpecification widthMeasureSpec, MeasureSpecification heightMeasureSpec)

    protected virtual void OnLayout(bool changed, LayoutLength left, LayoutLength top, LayoutLength right, LayoutLength bottom)

    protected virtual void OnSizeChanged(LayoutSize newSize, LayoutSize oldSize)

    public virtual void OnUnparent()

    protected virtual void OnAttachedToOwner()

src/Tizen.NUI/src/public/Layouting/LayoutLength.cs
public struct LayoutLength
  public LayoutLength(int value)
  public LayoutLength(float value)
  public LayoutLength(LayoutLength layoutLength)
  public float AsRoundedValue()
  public float AsDecimal()
  public static bool operator ==(LayoutLength arg1, LayoutLength arg2)
  public static bool operator !=(LayoutLength arg1, LayoutLength arg2)
  public override bool Equals(object obj)
  public bool Equals(LayoutLength layoutLength)
  public static LayoutLength operator +(LayoutLength arg1, LayoutLength arg2)
  public override int GetHashCode()
  public static LayoutLength operator +(LayoutLength arg1, int arg2)
  public static LayoutLength operator -(LayoutLength arg1, LayoutLength arg2)
  public static LayoutLength operator -(LayoutLength arg1, int arg2)
  public static LayoutLength operator *(LayoutLength arg1, LayoutLength arg2)
  public static LayoutLength operator *(LayoutLength arg1, int arg2)
  public static LayoutLength operator /(LayoutLength arg1, LayoutLength arg2)
  public static LayoutLength operator /(LayoutLength arg1, int arg2)

src/Tizen.NUI/src/public/Layouting/LayoutSize.cs
  public struct LayoutSize
  public LayoutSize(int width, int height)
  public override int GetHashCode()
  public override bool Equals(object obj)
  public static bool operator ==(LayoutSize lhs, LayoutSize rhs)
  public static bool operator !=(LayoutSize lhs, LayoutSize rhs)
  public int Width{ get; private set; }
  public int Height{ get; private set; }

src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
  public class LinearLayout 

  public LinearLayout()

  public enum Orientation
 	Horizontal,
        Vertical

  public enum Alignment
              Begin              = 0x1,
              End                = 0x2,
              CenterHorizontal   = 0x4,
              Top                = 0x8,
              Bottom             = 0x10,
              CenterVertical     = 0x20,
	      Center = 0x40

  public LinearLayout.Orientation LinearOrientation
  public Size2D CellPadding
  public LinearLayout.Alignment LinearAlignment
  protected override void OnMeasure(MeasureSpecification widthMeasureSpec, MeasureSpecification heightMeasureSpec)
  protected override void OnLayout(bool changed, LayoutLength left, LayoutLength top, LayoutLength right, LayoutLength bottom)

src/Tizen.NUI/src/public/Layouting/MeasureSpecification.cs
   public struct MeasureSpecification
   public LayoutLength Size;
   public MeasureSpecification.ModeType Mode;
   public MeasureSpecification(LayoutLength size, MeasureSpecification.ModeType mode)
   public enum ModeType {Unspecified, Exactly, AtMost}

src/Tizen.NUI/src/public/Layouting/MeasuredSize.cs
  public struct MeasuredSize
  public MeasuredSize(LayoutLength measuredSize, MeasuredSize.StateType state)
  public static implicit operator MeasuredSize(LayoutLength measuredSize)
  public LayoutLength Size{ get; set;}
  public StateType State{ get; set; }
  public enum StateType {MeasuredSizeOK, MeasuredSizeTooSmall}

src/Tizen.NUI/src/public/BaseComponents/View.cs
  public LayoutTransition LayoutTransition
  public float Weight

/public/Layouting/LayoutTransition.cs

   public class TransitionList
   public enum AnimatableProperties
   public class TransitionComponents
   public TransitionComponents()
   public TransitionComponents(int delay, int duration, AlphaFunction alphaFunction)
   public class LayoutTransition
   public LayoutTransition()
   public LayoutTransition( TransitionCondition condition,
                                 AnimatableProperties animatableProperty,
                                 object targetValue,
                                 TransitionComponents animator)
   public TransitionCondition Condition
   public AnimatableProperties AnimatableProperty
   public TransitionComponents Animator
   public object TargetValue

### CODE REVIEW

**Comment by agnelovaz** [comment]
Hi @dongsug-song  
I've removed the hidden API tags from LayoutTransitions.cs and LayoutData.cs and replaced them with <since> 5.5 </since>.   Is that correct?

Also are the changes I've made okay to merge into Samsung/TizenFX as they are or do they need tags to please the TizenBot as the ACR will need approving.

**Comment by dongsug-song** [comment]
Hello, Mr. Agnelo
After the ACR ( http://suprem.sec.samsung.net/jira/browse/TCSACR-278, it's been started already ) is accepted, then this PR can be merged. 
Also, please change the <since_tizen> 5.5 to <since_tizen> 6.
Thank you.

**Comment by agnelovaz** [comment]
Hi Ssong

The ACR reviewer wants 2 things:

1) A Samsung/TizenFX github patch ID, not a DaliHub/TizenFX, hence should I merge this request into dalihub and then you or me do a pull request into Samsung/TizenFX, providing that pull request link to the ACR -http://suprem.sec.samsung.net/jira/browse/TCSACR-278,

2) Design documents, I have those in the SRUK confluence, is there a place in the main Samsung confluence I can copy it?

thanks

**Comment by dongsug-song** [comment]
@agnelovaz 
Hello,
Basically, this kind of patch can be merged after ACR is accepted.
Let's wait...
( anyway, you can use this PR for ACR description; https://github.com/Samsung/TizenFX/pull/1014 )

For the design page, here is good example => http://suprem.sec.samsung.net/jira/browse/TCSACR-248 => •Design page： http://suprem.sec.samsung.net/confluence/display/API/%5B3%5D+Namespace%3A+Tizen.NUI.Components

and you can create new design page under this category => http://suprem.sec.samsung.net/confluence/display/API/%5B3%5D+Namespace%3A+Tizen.NUI
=> example: http://suprem.sec.samsung.net/confluence/display/API/Window+class%2C+NUI+Constants%3A+TCSACR-180

Please check the links above.
Thank you.

**Comment by agnelovaz** [comment]
Samsung/TizenFX pull request for ACR
https://github.com/Samsung/TizenFX/pull/1014

**Comment by dongsug-song** [comment]
changed as https://github.com/Samsung/TizenFX/pull/1022
thank you.

**Pull request closed without merging**
