### PR TITLE
[NUI.Components] Open public apis of Components for ACR

### PR DESCRIPTION
**Pull request by elishateng**
### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by dongsug-song** [comment]
Hello,
does this patch include the change of enabling View attribute setting?
OR is this only for ACR? 
please update TCSACR link here also.
thank you.

**Comment by dongsug-song** [comment]
Hello, All
Let's talk here about NUI.Components ACR~
we need to hide style and attribute related APIs, but I can see many of them.
please update TCSACR link here.
thank you.

**Comment by hyunjushin** [comment]
please hide all style, attribute & theme related APIs. We will have redesign for apply attribute, do not open on API version 6.
do not open every class in Attribute folder.
do not open constructor with style and attributes parameters.
do not open GetAttributes() method.
do not open ThemeChangeEventArgs

**Comment by hyunjushin** [comment]
please hide all classes in "flexibleview" folder. Layout will be added from Tizen 5.5(API 6).

**Comment by hyunjushin** [comment]
Please hide DropDown.cs at first. As I know, it is only ui component which is using "FlexibleView" in flexiblefolder. I wish Agnelo refactoring the class with new Layout. After then we can open DropDown.cs.

**Comment by AdunFang** [comment]
This pull request has been override by https://github.com/dalihub/TizenFX/pull/27

**Pull request closed without merging**
